#!/usr/bin/env bash

# author: Longhao.Chen <Longhao.Chen@outlook.com>
# https://github.com/Longhao-Chen/nofail

printHelp() {
	echo "nofail v1.0.2"
	echo "usage: $0 [-h] [-?] [-s sleep] [-r max_retry] shell_command"
	echo "	-h show this help"
	echo "	-? show this help"
	echo "	[-s sleep] Command failure retry interval. Default: 1"
	echo "	[-r max_retry] Maximum number of retries. 0 is infinite retry. Default: 0"
	echo ""
	echo "Author: Longhao.Chen <Longhao.Chen@outlook.com>"
	echo "Issues: https://github.com/Longhao-Chen/nofail/issues"
	exit 1
}

# default value
sleep_time=1
max_retry=0 # 0 is infinite retry

# Parse parameters
while getopts "hmr:?m:s:r" arg; do
	case $arg in
	h) printHelp ;;
	s) sleep_time=$OPTARG ;;
	r) max_retry=$OPTARG ;;
	?) printHelp ;;
	esac
done
shift $(($OPTIND - 1))

retry=0
while true; do
	if $*; then
		exit 1
	fi
	retry=$((${retry} + 1))
	if [ ${retry} == ${max_retry} ]; then
		echo "Exit. Retried ${retry}."
		exit 0
	fi
	echo "Fail. Retried ${retry}."
	sleep ${sleep_time}
done
